//go:build !ignore_autogenerated
// +build !ignore_autogenerated

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto copies all properties into another MyApp.
func (in *MyApp) DeepCopyInto(out *MyApp) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy creates a deep copy of MyApp.
func (in *MyApp) DeepCopy() *MyApp {
	if in == nil {
		return nil
	}
	out := new(MyApp)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject implements runtime.Object.
func (in *MyApp) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto copies all properties into another MyAppList.
func (in *MyAppList) DeepCopyInto(out *MyAppList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]MyApp, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy creates a deep copy of MyAppList.
func (in *MyAppList) DeepCopy() *MyAppList {
	if in == nil {
		return nil
	}
	out := new(MyAppList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject implements runtime.Object.
func (in *MyAppList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto copies all properties into another MyAppSpec.
func (in *MyAppSpec) DeepCopyInto(out *MyAppSpec) {
	*out = *in
	if in.Resources != nil {
		in, out := &in.Resources, &out.Resources
		*out = new(ResourceSpec)
		**out = **in
	}
}

// DeepCopy creates a deep copy of MyAppSpec.
func (in *MyAppSpec) DeepCopy() *MyAppSpec {
	if in == nil {
		return nil
	}
	out := new(MyAppSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto copies all properties into another MyAppStatus.
func (in *MyAppStatus) DeepCopyInto(out *MyAppStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]metav1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy creates a deep copy of MyAppStatus.
func (in *MyAppStatus) DeepCopy() *MyAppStatus {
	if in == nil {
		return nil
	}
	out := new(MyAppStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto copies ResourceSpec.
func (in *ResourceSpec) DeepCopyInto(out *ResourceSpec) {
	*out = *in
}

// DeepCopy creates a deep copy of ResourceSpec.
func (in *ResourceSpec) DeepCopy() *ResourceSpec {
	if in == nil {
		return nil
	}
	out := new(ResourceSpec)
	in.DeepCopyInto(out)
	return out
}
